=== honeybadger-graphics/YG5YAO_XMLGyak/YG5YAO_1025/SaxYG5YAO/src/resources/YG5YAO_kurzusfelvetel.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/YG5YAO_kurzusfelvetel" elementFormDefault="qualified">

    <!--egyszeru tipusok, kigyujtese hivatkozas celjabol-->
    <xs:attribute name="tanev" type="tanevTipus"/>
    <xs:attribute name="egyetem" type="egyetemTipus"/>
    <xs:element name="hnev" type="xs:string" />
    <xs:element name="szulev" type="xs:string" />
    <xs:element name="szak" type="szakTipus"/>
    <xs:attribute name="hid" type="idHallgatoTipus"/>
    <xs:attribute name="evf" type="evfTipus"/>
    
    <xs:element name="kurzusnev" type="xs:string"/>
    <xs:element name="kredit" type="xs:integer"/>
    <xs:element name="hely" type="xs:string"/>
    <xs:element name="idopont" type="xs:string"/>
    <xs:element name="oktato" type="xs:string"/>
    <xs:element name="gyakvezer" type="xs:string"/>
    <xs:attribute name="id" type="idKurzusTipus"/>
    <xs:attribute name="nyelv" type="nyelvTipus"/>
    <xs:attribute name="jovahagy" type="igenNemTipus"/>

     <!--egyszeru saját tipusok tipusok-->
    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}/[0-9]{4}_[1-2]{1}"/>
        </xs:restriction> 
    </xs:simpleType>
    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="ME"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="idHallgatoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="idKurzusTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{5}[0-9]{3}-B|[A-Z]{5}[0-9]{3}-BL"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="igen|nem"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nyelvTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="magyar|angol|német"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="evfTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="20"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name = "szakTipus">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="evf" type="xs:int"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
     <!--complex tipusok-->
     <xs:element name="YG5YAO_kurzusfelvetel">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name= "hallgato">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="hnev"/>
                                <xs:element ref="szulev"/>
                                <xs:element ref="szak" />
                            </xs:sequence>
                        <xs:attribute ref="hid" use="required"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="kurzusok">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name= "kurzus" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="kurzusnev"/>
                                        <xs:element ref="kredit"/>
                                        <xs:element ref="hely" minOccurs="1" maxOccurs="2"/>
                                        <xs:element ref="idopont" minOccurs="1" maxOccurs="2"/>
                                        <xs:element ref="oktato" />
                                        <xs:element ref="gyakvezer" minOccurs="0" maxOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                    <xs:attribute ref="nyelv"/>
                                    <xs:attribute ref="jovahagy"/>
                                </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute ref="tanev" use="required"/>
                <xs:attribute ref="egyetem" use="required"/>
            </xs:complexType>
        </xs:element>
</xs:schema>

=== honeybadger-graphics/YG5YAO_XMLGyak/YG5YAO_1025/SaxYG5YAO/src/resources/YG5YAO_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <YG5YAO_kurzusfelvetel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	xsi:noNamespaceSchemaLocation="YG5YAO_kurzusfelvetel.xsd" tanev="2023/2024_1" egyetem="ME">-->
    <YG5YAO_kurzusfelvetel tanev="2023/2024_1" egyetem="ME">
	<hallgato hid="YG5YAO">
        <hnev>Simko Levente</hnev>
        <szulev>1998</szulev>
        <szak evf="5">Mernokinformatikus</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="GEIAL332-B" >
            <kurzusnev>Adatkezeles XMLben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII A1 magasfsz</hely>
            <hely>In/202 In II. e. 202</hely>
            <idopont>Kedd 12-14</idopont>
            <idopont>Szerda 10-12</idopont>
            <oktato>Dr. Bednarik Laszlo</oktato>
        </kurzus>
        <kurzus id="GEIAL331-B" nyelv="magyar">
            <kurzusnev>WEB technologiak</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX A1 III. em. 305-306</hely>
            <hely>In/101 In I. e. 101</hely>
            <idopont>Hetfo 14-16</idopont>
            <idopont>Hetfo 16-18</idopont>
            <oktato>Agardi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAL336-B" jovahagy="igen">
            <kurzusnev>WEBes alkalmazasok CSharp</kurzusnev>
            <kredit>5</kredit>
            <hely>In/101 In I. e. 101</hely>
            <idopont>14-18</idopont>
            <oktato>Arvai Laszlo</oktato>
            <gyakvezer>Dr. Mileff Peter</gyakvezer>
        </kurzus>
    </kurzusok>
</YG5YAO_kurzusfelvetel>
